package objVirtual;
// Generated 05/06/2011 10:40:41 PM by Hibernate Tools 3.2.1.GA



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String direccion;
     private String telefono;

    public Cliente() {
    }

    public Cliente(String nombre, String direccion, String telefono) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


