package objVirtual;
// Generated 29/05/2011 07:14:58 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;






/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements Serializable  {


     private long id;
     private long idCliente;
     private long idProveedor;
     private String mensaje;
     private boolean estado;

    public Pedido() {
    }

    public Pedido( long idCliente, long idProveedor, String mensaje, boolean estado) {
       this.idCliente = idCliente;
       this.idProveedor = idProveedor;
       this.mensaje = mensaje;
       this.estado = estado;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(long idCliente) {
        this.idCliente = idCliente;
    }
    public long getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(long idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


