package vo;
// Generated 09/06/2011 05:53:40 PM by Hibernate Tools 3.2.1.GA



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  extends PersistenceObj implements java.io.Serializable {


     private Long id;
     private Credenciales credenciales;
     private String nombre;
     private String direccion;
     private String telefono;

    public Proveedor() {
    }

    public Proveedor(Credenciales credenciales, String nombre, String direccion, String telefono) {
       this.credenciales = credenciales;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Credenciales getCredenciales() {
        return this.credenciales;
    }
    
    public void setCredenciales(Credenciales credenciales) {
        this.credenciales = credenciales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


